os:
  - linux
  - osx

sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libx11-dev
      - libxkbfile-dev

before_install:
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 4.1
  - nvm use 4.1
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - $CXX --version
  - npm i

script:
  - npm test

git:
  depth: 10

branches:
  only:
    - master
